#!/usr/bin/env bash
#
# merge-fleet.sh — one-shot, self-verifying fleet merge executor
# ---------------------------------------------------------------
# Generated by codex R383 (2026-09-26) from MERGE-RUNBOOK-2026-09-24.md,
# after a LIVE merge-readiness audit (isDraft + mergeable + mergeStateStatus + baseRefName)
# confirmed ZERO drift since R382. Every target below was MERGEABLE/CLEAN at generation time.
#
# WHY THIS EXISTS: the runbook is 30+ interdependent commands across 5 agent repos + 3
# non-agent repos (merges, base-retargets, keystone hand-close loops, draft skips). Typing
# them by hand is the friction that has left the fleet at 0 merges for ~2 weeks. This script
# does the whole thing in the correct dependency order with a live safety check before EVERY
# action, so it can never die mid-run, never merge a draft, and never no-op a stacked base.
#
# GOVERNANCE: this script EXECUTES NOTHING by itself. It is DRY-RUN by default (prints the
# plan). The merge decision is still 100% the owner's — you break the stall by running:
#
#     ./merge-fleet.sh              # dry run: print exactly what WOULD happen, touch nothing
#     ./merge-fleet.sh --execute    # actually merge/close/retarget (owner action)
#     ./merge-fleet.sh --execute --only jobscout   # run one repo section only
#
# Sections: jobscout | community | efa | content | avrg | grant | psychic | linkinbio | kaivault
# Requires: gh (authenticated). No other dependencies.
#
set -uo pipefail

OWNER="morrisstephon51"
DRY=1
ONLY=""
for a in "$@"; do
  case "$a" in
    --execute) DRY=0 ;;
    --only) ONLY="__next__" ;;
    --dry-run) DRY=1 ;;
    *) if [ "$ONLY" = "__next__" ]; then ONLY="$a"; fi ;;
  esac
done

MERGED=0; CLOSED=0; RETARGETED=0; ISSUES_CLOSED=0; SKIPPED=0

c_grn=$'\033[32m'; c_yel=$'\033[33m'; c_red=$'\033[31m'; c_dim=$'\033[2m'; c_rst=$'\033[0m'
say()  { printf '%s\n' "$*"; }
head() { printf '\n%s== %s ==%s\n' "$c_dim" "$*" "$c_rst"; }
run()  { # echo + (maybe) execute
  if [ "$DRY" -eq 1 ]; then printf '   %s[dry]%s %s\n' "$c_dim" "$c_rst" "$*";
  else printf '   %s[run]%s %s\n' "$c_grn" "$c_rst" "$*"; eval "$@"; fi
}
want() { [ -z "$ONLY" ] || [ "$ONLY" = "$1" ]; }

# ready <repo> <pr>  ->  prints one of: READY | DRAFT | UNMERGEABLE:<state> | GONE
# Uses gh's built-in --jq (gojq) so booleans render lowercase true/false.
# Polls up to 3x because GitHub briefly reports mergeable=UNKNOWN right after a merge.
ready() {
  local R="$1" n="$2" try line state draft mrg
  for try in 1 2 3; do
    line=$(gh pr view "$n" -R "$R" --json isDraft,mergeable,state \
             --jq '"\(.state)|\(.isDraft)|\(.mergeable)"' 2>/dev/null) || { echo "GONE"; return; }
    IFS='|' read -r state draft mrg <<<"$line"
    [ "$state" = "OPEN" ] || { echo "GONE"; return; }
    [ "$draft" = "true" ] && { echo "DRAFT"; return; }
    case "$mrg" in
      MERGEABLE) echo "READY"; return ;;
      UNKNOWN)   sleep 3 ;;   # recomputing after a prior merge; retry
      *)         echo "UNMERGEABLE:$mrg"; return ;;
    esac
  done
  echo "UNMERGEABLE:UNKNOWN"
}

# merge_ready <repo> <pr> <note>   — merge only if live-verified READY
merge_ready() {
  local R="$OWNER/$1" n="$2" note="$3" st
  st=$(ready "$R" "$n")
  case "$st" in
    READY) run "gh pr merge $n --repo $R --merge   # $note"; [ "$DRY" -eq 0 ] && MERGED=$((MERGED+1)) || MERGED=$((MERGED+1)) ;;
    DRAFT) say "   ${c_yel}[skip]${c_rst} #$n is a DRAFT -> OWNER-ONLY (Mark ready for review first). $note"; SKIPPED=$((SKIPPED+1)) ;;
    GONE)  say "   ${c_dim}[skip]${c_rst} #$n already merged/closed (not open). $note"; ;;
    *)     say "   ${c_red}[skip]${c_rst} #$n is $st -> author must rebase on new default before merging. $note"; SKIPPED=$((SKIPPED+1)) ;;
  esac
}

# close_pr <repo> <pr> <comment>
close_pr() {
  local R="$OWNER/$1" n="$2" cmt="$3" st
  st=$(gh pr view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
  if [ "$st" = "OPEN" ]; then run "gh pr close $n --repo $R --comment \"$cmt\""; CLOSED=$((CLOSED+1));
  else say "   ${c_dim}[skip]${c_rst} PR #$n already $st."; fi
}

# retarget <repo> <pr> <base>
retarget() {
  local R="$OWNER/$1" n="$2" base="$3" st
  st=$(gh pr view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
  if [ "$st" != "OPEN" ]; then say "   ${c_dim}[skip]${c_rst} PR #$n is $st -> nothing to retarget."; return 0; fi
  run "gh pr edit $n --repo $R --base $base"; RETARGETED=$((RETARGETED+1))
}

# close_issues <repo> <comment> <n...>
close_issues() {
  local R="$OWNER/$1"; shift; local cmt="$1"; shift
  for n in "$@"; do
    st=$(gh issue view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
    if [ "$st" = "OPEN" ]; then run "gh issue close $n --repo $R --comment \"$cmt\""; ISSUES_CLOSED=$((ISSUES_CLOSED+1));
    else say "   ${c_dim}[skip]${c_rst} issue #$n already $st."; fi
  done
}

# require_merged <repo> <pr> <what-depends-on-it>   -> 0 = proceed, 1 = HOLD
# R389: EVERY "fixed by X" / "superseded by X" follow-up must be GATED on X actually
# landing. R388 found this on agent_I_content #9/#8 and patched that ONE site inline;
# the audit it asked for found the same class at 39x the scale -- JobScout's 15 hand-closes
# and Community's 12 PR-closes + 12 issue-closes were ALL unconditional, so a keystone that
# merge_ready turned into a [skip] left 39 actions marking work DONE with no covering code
# on default. Harness-proven: with #61 and #38 forced UNMERGEABLE the unpatched script
# merged 21/23 and still fired all 39.
# In EXECUTE mode the gate is the real thing: state must be MERGED.
# In DRY mode there is no merge to observe, so it PREDICTS from live mergeability rather
# than assuming success -- otherwise the dry run would promise 27 issue-closes that the
# execute run would correctly refuse.
require_merged() {
  local R="$OWNER/$1" n="$2" what="$3" st why
  if [ "$DRY" -eq 1 ]; then
    st=$(ready "$R" "$n")
    [ "$st" = "READY" ] && return 0
    if [ "$st" = "GONE" ]; then
      [ "$(gh pr view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo '?')" = "MERGED" ] && return 0
      why="is already closed WITHOUT merging"
    else
      why="will not merge ($st)"
    fi
  else
    st=$(gh pr view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
    [ "$st" = "MERGED" ] && return 0
    why="did not merge (state=$st)"
  fi
  say "   ${c_red}[HOLD]${c_rst} #$n $why -> SKIPPING $what."
  say "   ${c_dim}         ${c_rst} Doing it anyway would mark that work DONE with no covering code on default."
  SKIPPED=$((SKIPPED+1))
  return 1
}

# warn_unless_merged <repo> <pr> <consequence>
# For a dependency where holding the follow-up would be WORSE than proceeding: EFA #29
# carries the real code fix for #28 and auto-closes it via a closing keyword, so blocking
# #29 because its guard (#32) skipped would withhold a correct fix. Warn loudly instead.
warn_unless_merged() {
  local R="$OWNER/$1" n="$2" consequence="$3" st
  # NB: written as if/else on purpose. `A && { ...; } || { ...; }` also runs the ||
  # branch whenever the && body merely returns false, which is not the intent here.
  if [ "$DRY" -eq 1 ]; then
    st=$(ready "$R" "$n")
    [ "$st" = "READY" ] && return 0
  else
    st=$(gh pr view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
    [ "$st" = "MERGED" ] && return 0
  fi
  say "   ${c_yel}[WARN]${c_rst} #$n did not land -> $consequence"
}

[ "$DRY" -eq 1 ] && say "${c_yel}DRY RUN${c_rst} — nothing will change. Re-run with ${c_grn}--execute${c_rst} to perform the merges." \
                 || say "${c_grn}EXECUTE MODE${c_rst} — performing live merges/closes."

# resolve_test_line_conflict <repo> <pr> <headBranch> <baseBranch>
# R388: agent_I_content #9 (glob runner) add/add-conflicts with #4 on package.json's
# "test" key once #4 lands — both write the SAME new key with DIVERGENT values, so the
# SET conflicts even though each PR reads MERGEABLE against its own base. Verified by
# local test-merge (R388): 2->4->6 clean, then 9 => "CONFLICT (content): package.json".
# The resolution is always #9's glob line: it auto-discovers every *.test.ts, so the
# enumerated line it replaces loses nothing (verified — the glob picks up all 4 files).
# This merges default into the PR branch, keeps the glob line, and pushes, which flips
# #9 back to MERGEABLE so the normal merge_ready call below can proceed.
resolve_test_line_conflict() {
  local R="$OWNER/$1" n="$2" hb="$3" bb="$4" st wd
  st=$(ready "$R" "$n")
  case "$st" in
    READY) say "   ${c_dim}[skip]${c_rst} #$n is already MERGEABLE — no conflict to resolve." ; return 0 ;;
    GONE)  say "   ${c_dim}[skip]${c_rst} #$n already merged/closed." ; return 0 ;;
    DRAFT) say "   ${c_yel}[skip]${c_rst} #$n is a DRAFT -> owner-only." ; return 1 ;;
  esac
  say "   ${c_yel}#$n is $st${c_rst} — resolving the package.json \"test\" conflict to the glob runner."
  if [ "$DRY" -eq 1 ]; then
    printf '   %s[dry]%s git merge %s into %s, keep "test": "ts-node scripts/run-tests.ts", push\n' "$c_dim" "$c_rst" "$bb" "$hb"
    return 0
  fi
  wd=$(mktemp -d) || return 1
  (
    set -e
    git clone -q --branch "$hb" "https://github.com/$R.git" "$wd/repo"
    cd "$wd/repo"
    git fetch -q origin "$bb"
    git merge --no-edit "origin/$bb" >/dev/null 2>&1 || true
    # package.json must be the ONLY conflicted path; anything else is unexpected -> abort.
    local conflicted; conflicted=$(git diff --name-only --diff-filter=U)
    [ "$conflicted" = "package.json" ] || { echo "unexpected conflicts: $conflicted"; exit 1; }
    python3 - <<'RESOLVE'
import json, re
s = open('package.json').read()
# We are ON the PR branch merging the base IN, so HEAD ("ours") is the PR branch's
# glob-runner line and the incoming side is #4's enumerated line. Keep OURS.
# (Getting this backwards is silent-but-wrong, hence the assert below.)
s = re.sub(r'<<<<<<< [^\n]*\n(.*?)=======\n.*?>>>>>>> [^\n]*\n', r'\1', s, flags=re.S)
cfg = json.loads(s)
assert cfg['scripts']['test'] == 'ts-node scripts/run-tests.ts', cfg['scripts']['test']
open('package.json','w').write(s)
RESOLVE
    git add package.json
    git -c user.name=codex -c user.email=noreply@github.com commit -q -m "merge $bb: keep the glob test runner

#4 and this branch both add package.json's \"test\" key with different values.
Resolved to the glob runner — it auto-discovers every *.test.ts, so the
enumerated line it replaces drops no tests."
    git push -q origin "$hb"
  )
  local rc=$?
  rm -rf "$wd"
  if [ $rc -ne 0 ]; then
    say "   ${c_red}[FAILED]${c_rst} could not auto-resolve #$n — resolve package.json by hand, then re-run."
    SKIPPED=$((SKIPPED+1))
  fi
  return $rc
}

# ─────────────────────────────────────────────────────────────────────────────
# 1. JobScout  (default claude/clever-cannon-IDh3G)
#    #61 keystone (salary/cadence regex families) — NO closing keyword -> hand-close.
#    #61 and #63 both edit scorer.py: merge #61 first; #63's live guard catches any conflict.
if want jobscout; then head "1. JobScout — job_opportunity_scanner"
  merge_ready job_opportunity_scanner 61 "keystone: salary-cadence regex families (no closing kw -> hand-close below)"
  merge_ready job_opportunity_scanner 63 "whole-word SEARCH_KEYWORDS match (closes #62) [guarded vs #61 conflict]"
  merge_ready job_opportunity_scanner 25 "salary-range placeholder-0 / shared-k fix"
  merge_ready job_opportunity_scanner 27 "recency: 'X years ago' past MAX_DAYS_OLD (closes #26)"
  merge_ready job_opportunity_scanner 65 "AGENCY_BLOCKLIST 'TEKsystems' one-word match (closes #64)"
  merge_ready job_opportunity_scanner 67 "sync /scan prompt to scorer/config, restore 'trainer' (closes #66)"
  # R390: residual site of the same #66 class -- #67 reconciled the prompt's SCORING copies
  # (Step 3 filter, Step 4 table) but not its QUERY list. 2 of 8 config.SEARCH_KEYWORDS
  # ("EdTech coordinator", "learning experience designer") appeared nowhere in the prompt, so
  # they were scored but never searched. Order-independent: test-merged live against all six
  # siblings in BOTH orders, scan.md auto-merges (#67 = Steps 3-4, #69 = Steps 1-2), 16/16
  # test files exit 0 either way. Auto-closes #68 via a body keyword -- no hand-close needed.
  merge_ready job_opportunity_scanner 69 "/scan issues one query per config.SEARCH_KEYWORDS (closes #68) [disjoint from #67]"
  # GATED (R389): these 15 issues are closed as "Fixed by #61" -- only true if #61 landed.
  if require_merged job_opportunity_scanner 61 "the 15 hand-closes for issues #30-#59"; then
    close_issues job_opportunity_scanner \
      "Fixed by #61 (anchored salary/cadence regex families; superset-proven in a fresh Python 3.14 clone). #61 lacked a closing keyword, closing manually." \
      30 32 34 36 38 41 43 45 47 49 51 53 55 57 59
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# 2. Community Intake  (default claude/quirky-galileo-UGnfz)
#    #38 keystone (intent classifier) supersets the #14-#36 tower. NO closing keyword.
#    10 sibling PRs sit on non-default fix/* bases -> CLOSE (merging them = silent no-op).
if want community; then head "2. Community Intake — -Community_intake_Routing"
  merge_ready -Community_intake_Routing 38 "keystone intent-based classifier (no closing kw -> hand-close below)"
  # R386 (execution-proven): ran all 12 sibling suites against #38 -> #15/#17/#19/#21/#35 pass
  # clean; #23 reports 50/52 but that failing line is the already-merged `#3` assertion that #23
  # INVERTED to accommodate its token deletion. #38 keeps #3 AND fixes #22 (seek-vs-offer logic).
  # #25/#27/#29/#31/#33/#37 are stacked on #23 and inherit the inverted line. NEVER merge #23:
  # it routes genuine volunteers ("I want to mentor first-gen students") to the learner default.
  # GATED (R389): the highest-stakes dependency in the whole script. These 12 PRs are the
  # ONLY other fixes for these 12 issues -- closing them as "superseded" while #38 is absent
  # erases the entire fix surface for this repo and leaves 12 issues closed as fixed.
  if require_merged -Community_intake_Routing 38 "the 12 sibling PR-closes AND the 12 issue hand-closes"; then
    for n in 15 17 19 21 23 25 27 29 31 33 35 37; do
      close_pr -Community_intake_Routing "$n" "Superseded by #38 (superset re-proven 2026-09-26 by running this branch's own suite against #38; see the evidence comment on #38). Closing to avoid a non-default-base no-op."
    done
    close_issues -Community_intake_Routing \
      "Fixed by #38 (intent-based classifier; proven behavioral superset of the #14-#36 tower, 94/94 tests). #38 lacked a closing keyword, closing manually." \
      14 16 18 20 22 24 26 28 30 32 34 36
  fi
  merge_ready -Community_intake_Routing 40 "web /api/intake email-routing parity (closes #39) — independent of classify"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 3. Enrollment Funnel  (default claude/keen-noether-VED1j)
#    Merge #25 first (adds test/*.test.ts glob runner). #29 & #31 both touch scorer.ts;
#    #31's live guard catches any conflict introduced by #29.
if want efa; then head "3. Enrollment Funnel — Enrollment_Funnel_Agent"
  merge_ready Enrollment_Funnel_Agent 25 "GA4 'Sessions' thousand-separators + test-glob runner (first)"
  merge_ready Enrollment_Funnel_Agent 26 "trim GA4 UTM CSV so hand-edits don't zero sessions"
  merge_ready Enrollment_Funnel_Agent 27 "Meta alias whole-filename-token match"
  # R387: #32 is stacked on #29's branch (base=fix/unify-engagement-weights) and MUST merge
  # first so #29 carries a guard that can actually fail. Execution-proven: #29's own
  # engagement-parity.test.ts is a tautology (baselineTotal === currentWeekTotal, both sides
  # computed with computeEngagementScore; supabase.ts never imported). It PASSES on the
  # default branch and PASSES with the #28 drift re-injected as 1/99/99/99 in
  # fetchRollingEngagement. #32's structural guard fails on both. #29's CODE FIX is correct.
  merge_ready Enrollment_Funnel_Agent 32 "real #28 drift guard -> merges INTO #29's branch; run BEFORE #29"
  warn_unless_merged Enrollment_Funnel_Agent 32 "merging #29 below will auto-close issue #28 via its closing keyword, leaving ONLY #29's tautological engagement-parity.test.ts as the guard (it passes with the #28 drift re-injected). #29's code fix is correct, so it still merges -- but reopen #28 or rebase #32 afterwards."
  merge_ready Enrollment_Funnel_Agent 29 "unify weekly engagement weights, one formula (closes #28)"
  merge_ready Enrollment_Funnel_Agent 31 "surface empty engagement baseline vs false all-clear (refs #30) [guarded vs #29]"
  say "   ${c_dim}note:${c_rst} issue #30 (upsertPerformance persistence) + #24 (retire stale main) are OWNER-ONLY."
  say "   ${c_dim}note:${c_rst} R387 execution-verified: all 5 EFA PRs test-merge clean in BOTH orders (identical trees);"
  say "   ${c_dim}      ${c_rst} full suite 6/6 files green (incl. #32). #26/#29/#31 add tests but NO runner wiring —"
  say "   ${c_dim}      ${c_rst} #25 or #27 must land or no EFA test executes at all."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 4. Content Pipeline  (default claude/eloquent-edison-aF7yG)
#    #4 is stacked on #2's branch -> retarget to default before merging.
#    #9's glob runner supersedes #8's hand-wired package.json -> close #8.
if want content; then head "4. Content Pipeline — agent_I_content"
  merge_ready agent_I_content 2 "enforce CAPTION_LIMITS in code"
  retarget    agent_I_content 4 "claude/eloquent-edison-aF7yG"
  merge_ready agent_I_content 4 "enforce topic-derived hashtags + hashtag-filter.test.ts (closes #3)"
  merge_ready agent_I_content 6 "validate post.platform before insert (closes #5) — brings platform-validation.test.ts"
  resolve_test_line_conflict agent_I_content 9 "fix/test-runner-glob-union" "claude/eloquent-edison-aF7yG"
  merge_ready agent_I_content 9 "glob test runner scripts/run-tests.ts (auto-discovers all *.test.ts)"
  # #8 hand-wires platform-validation.test.ts into package.json. It is ONLY redundant if
  # #9's glob actually landed — closing it blind after a skipped #9 would leave that test
  # with no runner at all, which is the exact bug class this section exists to fix.
  # R388 gated this inline; R389 folds it into the shared require_merged helper so the
  # dry run also predicts the HOLD instead of assuming #9 lands.
  if require_merged agent_I_content 9 "closing #8 (the only runner wiring for platform-validation.test.ts)"; then
    close_pr  agent_I_content 8 "Superseded by #9: the glob runner auto-discovers platform-validation.test.ts (added by #6). #8 only hand-wired package.json, now redundant."
  fi
  merge_ready agent_I_content 10 "pipeline-wiring.test.ts — assert the 3 sanitizers are on the code path (MERGE LAST: asserts #2+#4+#6 are all present)"
  say "   ${c_yel}verify after:${c_rst} npm install && npm test on default -> expect 4/4 test files, 30/30 assertions."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 5. AI Video Reel Generator  (default main) — both PRs carry closing keywords (no hand-close)
if want avrg; then head "5. AI Video Reel Generator — ai-video-reel-generator"
  merge_ready ai-video-reel-generator 27 "remove unsatisfiable ADMIN_SECRET guard on browser-only routes (auto-closes #26 AND #28) — reverses hardening #14/#20, owner call"
  merge_ready ai-video-reel-generator 31 "anchor best-post-times to America/New_York not server UTC (auto-closes #30)"
  say "   ${c_dim}note:${c_rst} issue #5 (provision live Supabase) is OWNER-ONLY infra."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 5b. Grant Agent  (default claude/nifty-bohr-AhrsA) — the SIXTH agent repo, found R391
#     by reading PRs=0/ISSUES=0 as "never audited" rather than "clean".
#     Both PRs are based on the DEFAULT branch and both carry a body closing keyword
#     (closingIssuesReferences verified [2] and [4]), so there is NO hand-close loop here.
#     They add byte-identical tests/__init__.py + .github/workflows/tests.yml (the repo had
#     no runner at all), which add/add-merge cleanly; test-merged in BOTH orders, no
#     conflict, scorer suite green in the merged tree either way. Otherwise disjoint files
#     (scraper.py vs scorer.py), so this order is preference, not a dependency.
if want grant; then head "5b. Grant Agent — agent-II"
  merge_ready agent-II 3 "HTML scraper: treat a 403/404 error page as no content (auto-closes #2) — stops fabricated grants reaching the billed scorer, and un-blocks fallback_url"
  merge_ready agent-II 5 "scorer: validate Claude's response shape inside its own fallback (auto-closes #4) — 3 crash-after-billing shapes + 1 silent all-5/10 report"
  say "   ${c_dim}note:${c_rst} known limitation stated in #2, NOT fixed: google.org and the grants.gov"
  say "   ${c_dim}      ${c_rst} URL return HTTP 200 but are a landing page and a JS-rendered shell —"
  say "   ${c_dim}      ${c_rst} a status check cannot detect those. Owner call on replacing the targets."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6. Non-agent repos (owner's personal/business/vault — editorial call).
#    Draft PRs are auto-skipped by the live guard with an OWNER-ONLY message.
if want psychic; then head "6a. psychic-bassoon"
  merge_ready psychic-bassoon 1 "real content + working forms + resource detail pages (34 files, +7800; open since Jun 13)"
  merge_ready psychic-bassoon 25 "add /websites services page (DRAFT -> owner-only)"
fi
if want linkinbio; then head "6b. Link-inbio"
  merge_ready Link-inbio 15 "rebuild Command Center as live scroll dashboard (+2288/-541)"
  merge_ready Link-inbio 5 "Obsidian ops vault (DRAFT -> owner-only)"
  close_pr    Link-inbio 6 "Empty diff (+0/-0), 13 commits behind a diverged main -> resume PDF already on main or abandoned, and the fellowship deadline has passed. Closing as stale."
fi
if want kaivault; then head "6c. kai-obsidian-vault"
  merge_ready kai-obsidian-vault 3 "record theplugai.info scroll-homepage deployment (DRAFT -> owner-only)"
  merge_ready kai-obsidian-vault 2 "CHA Resident Business Owner Program business plan (DRAFT -> owner-only)"
fi

# ─────────────────────────────────────────────────────────────────────────────
head "SUMMARY"
say "   PRs merged:      $MERGED"
say "   PRs closed:      $CLOSED"
say "   PRs retargeted:  $RETARGETED"
say "   Issues closed:   $ISSUES_CLOSED"
say "   Skipped (draft/unmergeable/gone): $SKIPPED"
if [ "$DRY" -eq 1 ]; then
  say ""
  say "${c_yel}This was a DRY RUN.${c_rst} Re-run with ${c_grn}--execute${c_rst} to perform these actions."
fi
say ""
say "Owner-only remainders (no PR possible): EFA #30 schema-persist, EFA #24 retire main,"
say "avrg #5 Supabase provisioning, forming-paws #8 (IL-SOS filing), and any Section-6 DRAFT PR"
say "(psychic #25, Link-inbio #5, kai-vault #2/#3) until you 'Mark ready for review'."
