#!/usr/bin/env bash
#
# merge-fleet.sh — one-shot, self-verifying fleet merge executor
# ---------------------------------------------------------------
# Generated by codex R383 (2026-09-26) from MERGE-RUNBOOK-2026-09-24.md,
# after a LIVE merge-readiness audit (isDraft + mergeable + mergeStateStatus + baseRefName)
# confirmed ZERO drift since R382. Every target below was MERGEABLE/CLEAN at generation time.
#
# WHY THIS EXISTS: the runbook is 30+ interdependent commands across 5 agent repos + 3
# non-agent repos (merges, base-retargets, keystone hand-close loops, draft skips). Typing
# them by hand is the friction that has left the fleet at 0 merges for ~2 weeks. This script
# does the whole thing in the correct dependency order with a live safety check before EVERY
# action, so it can never die mid-run, never merge a draft, and never no-op a stacked base.
#
# GOVERNANCE: this script EXECUTES NOTHING by itself. It is DRY-RUN by default (prints the
# plan). The merge decision is still 100% the owner's — you break the stall by running:
#
#     ./merge-fleet.sh              # dry run: print exactly what WOULD happen, touch nothing
#     ./merge-fleet.sh --execute    # actually merge/close/retarget (owner action)
#     ./merge-fleet.sh --execute --only jobscout   # run one repo section only
#
# Sections: jobscout | community | efa | content | avrg | psychic | linkinbio | kaivault
# Requires: gh (authenticated). No other dependencies.
#
set -uo pipefail

OWNER="morrisstephon51"
DRY=1
ONLY=""
for a in "$@"; do
  case "$a" in
    --execute) DRY=0 ;;
    --only) ONLY="__next__" ;;
    --dry-run) DRY=1 ;;
    *) if [ "$ONLY" = "__next__" ]; then ONLY="$a"; fi ;;
  esac
done

MERGED=0; CLOSED=0; RETARGETED=0; ISSUES_CLOSED=0; SKIPPED=0

c_grn=$'\033[32m'; c_yel=$'\033[33m'; c_red=$'\033[31m'; c_dim=$'\033[2m'; c_rst=$'\033[0m'
say()  { printf '%s\n' "$*"; }
head() { printf '\n%s== %s ==%s\n' "$c_dim" "$*" "$c_rst"; }
run()  { # echo + (maybe) execute
  if [ "$DRY" -eq 1 ]; then printf '   %s[dry]%s %s\n' "$c_dim" "$c_rst" "$*";
  else printf '   %s[run]%s %s\n' "$c_grn" "$c_rst" "$*"; eval "$@"; fi
}
want() { [ -z "$ONLY" ] || [ "$ONLY" = "$1" ]; }

# ready <repo> <pr>  ->  prints one of: READY | DRAFT | UNMERGEABLE:<state> | GONE
# Uses gh's built-in --jq (gojq) so booleans render lowercase true/false.
# Polls up to 3x because GitHub briefly reports mergeable=UNKNOWN right after a merge.
ready() {
  local R="$1" n="$2" try line state draft mrg
  for try in 1 2 3; do
    line=$(gh pr view "$n" -R "$R" --json isDraft,mergeable,state \
             --jq '"\(.state)|\(.isDraft)|\(.mergeable)"' 2>/dev/null) || { echo "GONE"; return; }
    IFS='|' read -r state draft mrg <<<"$line"
    [ "$state" = "OPEN" ] || { echo "GONE"; return; }
    [ "$draft" = "true" ] && { echo "DRAFT"; return; }
    case "$mrg" in
      MERGEABLE) echo "READY"; return ;;
      UNKNOWN)   sleep 3 ;;   # recomputing after a prior merge; retry
      *)         echo "UNMERGEABLE:$mrg"; return ;;
    esac
  done
  echo "UNMERGEABLE:UNKNOWN"
}

# merge_ready <repo> <pr> <note>   — merge only if live-verified READY
merge_ready() {
  local R="$OWNER/$1" n="$2" note="$3" st
  st=$(ready "$R" "$n")
  case "$st" in
    READY) run "gh pr merge $n --repo $R --merge   # $note"; [ "$DRY" -eq 0 ] && MERGED=$((MERGED+1)) || MERGED=$((MERGED+1)) ;;
    DRAFT) say "   ${c_yel}[skip]${c_rst} #$n is a DRAFT -> OWNER-ONLY (Mark ready for review first). $note"; SKIPPED=$((SKIPPED+1)) ;;
    GONE)  say "   ${c_dim}[skip]${c_rst} #$n already merged/closed (not open). $note"; ;;
    *)     say "   ${c_red}[skip]${c_rst} #$n is $st -> author must rebase on new default before merging. $note"; SKIPPED=$((SKIPPED+1)) ;;
  esac
}

# close_pr <repo> <pr> <comment>
close_pr() {
  local R="$OWNER/$1" n="$2" cmt="$3" st
  st=$(gh pr view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
  if [ "$st" = "OPEN" ]; then run "gh pr close $n --repo $R --comment \"$cmt\""; CLOSED=$((CLOSED+1));
  else say "   ${c_dim}[skip]${c_rst} PR #$n already $st."; fi
}

# retarget <repo> <pr> <base>
retarget() {
  local R="$OWNER/$1" n="$2" base="$3"
  run "gh pr edit $n --repo $R --base $base"; RETARGETED=$((RETARGETED+1))
}

# close_issues <repo> <comment> <n...>
close_issues() {
  local R="$OWNER/$1"; shift; local cmt="$1"; shift
  for n in "$@"; do
    st=$(gh issue view "$n" -R "$R" --json state --jq '.state' 2>/dev/null || echo GONE)
    if [ "$st" = "OPEN" ]; then run "gh issue close $n --repo $R --comment \"$cmt\""; ISSUES_CLOSED=$((ISSUES_CLOSED+1));
    else say "   ${c_dim}[skip]${c_rst} issue #$n already $st."; fi
  done
}

[ "$DRY" -eq 1 ] && say "${c_yel}DRY RUN${c_rst} — nothing will change. Re-run with ${c_grn}--execute${c_rst} to perform the merges." \
                 || say "${c_grn}EXECUTE MODE${c_rst} — performing live merges/closes."

# ─────────────────────────────────────────────────────────────────────────────
# 1. JobScout  (default claude/clever-cannon-IDh3G)
#    #61 keystone (salary/cadence regex families) — NO closing keyword -> hand-close.
#    #61 and #63 both edit scorer.py: merge #61 first; #63's live guard catches any conflict.
if want jobscout; then head "1. JobScout — job_opportunity_scanner"
  merge_ready job_opportunity_scanner 61 "keystone: salary-cadence regex families (no closing kw -> hand-close below)"
  merge_ready job_opportunity_scanner 63 "whole-word SEARCH_KEYWORDS match (closes #62) [guarded vs #61 conflict]"
  merge_ready job_opportunity_scanner 25 "salary-range placeholder-0 / shared-k fix"
  merge_ready job_opportunity_scanner 27 "recency: 'X years ago' past MAX_DAYS_OLD (closes #26)"
  merge_ready job_opportunity_scanner 65 "AGENCY_BLOCKLIST 'TEKsystems' one-word match (closes #64)"
  merge_ready job_opportunity_scanner 67 "sync /scan prompt to scorer/config, restore 'trainer' (closes #66)"
  close_issues job_opportunity_scanner \
    "Fixed by #61 (anchored salary/cadence regex families; superset-proven in a fresh Python 3.14 clone). #61 lacked a closing keyword, closing manually." \
    30 32 34 36 38 41 43 45 47 49 51 53 55 57 59
fi

# ─────────────────────────────────────────────────────────────────────────────
# 2. Community Intake  (default claude/quirky-galileo-UGnfz)
#    #38 keystone (intent classifier) supersets the #14-#36 tower. NO closing keyword.
#    10 sibling PRs sit on non-default fix/* bases -> CLOSE (merging them = silent no-op).
if want community; then head "2. Community Intake — -Community_intake_Routing"
  merge_ready -Community_intake_Routing 38 "keystone intent-based classifier (no closing kw -> hand-close below)"
  for n in 15 17 19 21 23 25 27 29 31 33 35 37; do
    close_pr -Community_intake_Routing "$n" "Superseded by #38 (proven behavioral superset of the #14-#36 tower, 94/94 tests). Closing to avoid a non-default-base no-op."
  done
  close_issues -Community_intake_Routing \
    "Fixed by #38 (intent-based classifier; proven behavioral superset of the #14-#36 tower, 94/94 tests). #38 lacked a closing keyword, closing manually." \
    14 16 18 20 22 24 26 28 30 32 34 36
  merge_ready -Community_intake_Routing 40 "web /api/intake email-routing parity (closes #39) — independent of classify"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 3. Enrollment Funnel  (default claude/keen-noether-VED1j)
#    Merge #25 first (adds test/*.test.ts glob runner). #29 & #31 both touch scorer.ts;
#    #31's live guard catches any conflict introduced by #29.
if want efa; then head "3. Enrollment Funnel — Enrollment_Funnel_Agent"
  merge_ready Enrollment_Funnel_Agent 25 "GA4 'Sessions' thousand-separators + test-glob runner (first)"
  merge_ready Enrollment_Funnel_Agent 26 "trim GA4 UTM CSV so hand-edits don't zero sessions"
  merge_ready Enrollment_Funnel_Agent 27 "Meta alias whole-filename-token match"
  merge_ready Enrollment_Funnel_Agent 29 "unify weekly engagement weights, one formula (closes #28)"
  merge_ready Enrollment_Funnel_Agent 31 "surface empty engagement baseline vs false all-clear (refs #30) [guarded vs #29]"
  say "   ${c_dim}note:${c_rst} issue #30 (upsertPerformance persistence) + #24 (retire stale main) are OWNER-ONLY."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 4. Content Pipeline  (default claude/eloquent-edison-aF7yG)
#    #4 is stacked on #2's branch -> retarget to default before merging.
#    #9's glob runner supersedes #8's hand-wired package.json -> close #8.
if want content; then head "4. Content Pipeline — agent_I_content"
  merge_ready agent_I_content 2 "enforce CAPTION_LIMITS in code"
  retarget    agent_I_content 4 "claude/eloquent-edison-aF7yG"
  merge_ready agent_I_content 4 "enforce topic-derived hashtags + hashtag-filter.test.ts (closes #3)"
  merge_ready agent_I_content 6 "validate post.platform before insert (closes #5) — brings platform-validation.test.ts"
  merge_ready agent_I_content 9 "glob test runner scripts/run-tests.ts (auto-discovers all *.test.ts)"
  close_pr    agent_I_content 8 "Superseded by #9: the glob runner auto-discovers platform-validation.test.ts (added by #6). #8 only hand-wired package.json, now redundant."
  say "   ${c_yel}verify after:${c_rst} confirm scripts/run-tests.ts lists platform-validation.test.ts once #6+#9 are on default; if not, reopen+retarget+merge #8."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 5. AI Video Reel Generator  (default main) — both PRs carry closing keywords (no hand-close)
if want avrg; then head "5. AI Video Reel Generator — ai-video-reel-generator"
  merge_ready ai-video-reel-generator 27 "remove unsatisfiable ADMIN_SECRET guard on browser-only routes (auto-closes #26 AND #28) — reverses hardening #14/#20, owner call"
  merge_ready ai-video-reel-generator 31 "anchor best-post-times to America/New_York not server UTC (auto-closes #30)"
  say "   ${c_dim}note:${c_rst} issue #5 (provision live Supabase) is OWNER-ONLY infra."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6. Non-agent repos (owner's personal/business/vault — editorial call).
#    Draft PRs are auto-skipped by the live guard with an OWNER-ONLY message.
if want psychic; then head "6a. psychic-bassoon"
  merge_ready psychic-bassoon 1 "real content + working forms + resource detail pages (34 files, +7800; open since Jun 13)"
  merge_ready psychic-bassoon 25 "add /websites services page (DRAFT -> owner-only)"
fi
if want linkinbio; then head "6b. Link-inbio"
  merge_ready Link-inbio 15 "rebuild Command Center as live scroll dashboard (+2288/-541)"
  merge_ready Link-inbio 5 "Obsidian ops vault (DRAFT -> owner-only)"
  close_pr    Link-inbio 6 "Empty diff (+0/-0), 13 commits behind a diverged main -> resume PDF already on main or abandoned, and the fellowship deadline has passed. Closing as stale."
fi
if want kaivault; then head "6c. kai-obsidian-vault"
  merge_ready kai-obsidian-vault 3 "record theplugai.info scroll-homepage deployment (DRAFT -> owner-only)"
  merge_ready kai-obsidian-vault 2 "CHA Resident Business Owner Program business plan (DRAFT -> owner-only)"
fi

# ─────────────────────────────────────────────────────────────────────────────
head "SUMMARY"
say "   PRs merged:      $MERGED"
say "   PRs closed:      $CLOSED"
say "   PRs retargeted:  $RETARGETED"
say "   Issues closed:   $ISSUES_CLOSED"
say "   Skipped (draft/unmergeable/gone): $SKIPPED"
if [ "$DRY" -eq 1 ]; then
  say ""
  say "${c_yel}This was a DRY RUN.${c_rst} Re-run with ${c_grn}--execute${c_rst} to perform these actions."
fi
say ""
say "Owner-only remainders (no PR possible): EFA #30 schema-persist, EFA #24 retire main,"
say "avrg #5 Supabase provisioning, forming-paws #8 (IL-SOS filing), and any Section-6 DRAFT PR"
say "(psychic #25, Link-inbio #5, kai-vault #2/#3) until you 'Mark ready for review'."
